// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRlnRJdw7-R7q4bGX0ixResh3zMIY4UmE',
    appId: '1:783500905928:web:499bbd1d22c907c56b44fd',
    messagingSenderId: '783500905928',
    projectId: 'darna-app-65629',
    authDomain: 'darna-app-65629.firebaseapp.com',
    storageBucket: 'darna-app-65629.firebasestorage.app',
    measurementId: 'G-G13246CY18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcP_DrYrz9jZiyCQplOJ_rdMh5ZPm7qRk',
    appId: '1:783500905928:android:8125daa9af9876eb6b44fd',
    messagingSenderId: '783500905928',
    projectId: 'darna-app-65629',
    storageBucket: 'darna-app-65629.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALoVDjF-4WMrqU3b2juSZHB9AFHm2xfmk',
    appId: '1:783500905928:ios:6f133d414c4f8d936b44fd',
    messagingSenderId: '783500905928',
    projectId: 'darna-app-65629',
    storageBucket: 'darna-app-65629.firebasestorage.app',
    iosBundleId: 'com.example.darna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALoVDjF-4WMrqU3b2juSZHB9AFHm2xfmk',
    appId: '1:783500905928:ios:6f133d414c4f8d936b44fd',
    messagingSenderId: '783500905928',
    projectId: 'darna-app-65629',
    storageBucket: 'darna-app-65629.firebasestorage.app',
    iosBundleId: 'com.example.darna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRlnRJdw7-R7q4bGX0ixResh3zMIY4UmE',
    appId: '1:783500905928:web:01816cfac4b927876b44fd',
    messagingSenderId: '783500905928',
    projectId: 'darna-app-65629',
    authDomain: 'darna-app-65629.firebaseapp.com',
    storageBucket: 'darna-app-65629.firebasestorage.app',
    measurementId: 'G-PP9D9C07HY',
  );
}
